_INITIAL_SID_AND_ATTRIBUTES = _SID_AND_ATTRIBUTES
class _SID_AND_ATTRIBUTES(_INITIAL_SID_AND_ATTRIBUTES):
    pass

    # Only in TOKEN_GROUPS
    # attributes = FlagExatractor(_INITIAL_SID_AND_ATTRIBUTES.Attributes,
        # (SE_GROUP_MANDATORY,
        # SE_GROUP_ENABLED_BY_DEFAULT,
        # SE_GROUP_ENABLED,
        # SE_GROUP_OWNER,
        # SE_GROUP_USE_FOR_DENY_ONLY,
        # SE_GROUP_INTEGRITY,
        # SE_GROUP_INTEGRITY_ENABLED,
        # SE_GROUP_LOGON_ID,
        # SE_GROUP_RESOURCE))